# Operaciones matriciales (_librería **numpy**_)

In [1]:
import numpy as np

## Multiplicación y potencia
### Ejercicio 1
Con un calorímetro de bomba se realizó una serie de experimentos. En cada experimento se usó una cantidad diferente de agua. Calcule la capacidad calorífica total para el calorímetro en cada uno de los experimentos.

<figure style="text-align: center;">
  <div><strong>Fig. 1.</strong> Propiedades térmicas de un calorímetro de bomba. </div>
  <img src="markdown_resources\2.png" style="width: 40%; height: auto;">
  <figcaption>Tomado de MATLAB para Ingenieros de Holly Moore.</A>.</figcaption>
</figure>

<figure style="text-align: center;">
  <div><strong>Fig. 2.</strong> Capacidad calorímetra. </div>
  <img src="markdown_resources\3.png" style="width: 30%; height: auto;">
  <figcaption>Tomado de MATLAB para Ingenieros de Holly Moore.</A>.</figcaption>
</figure>

*Ejercicio tomado de Moore, 2007.*

### Solución

In [4]:
# Entrada
masa_agua = np.array([[110], [100], [101], [98.6], [99.4]])
masa_acero = np.array([[250], [250], [250], [250], [250]])
masa_aluminio = np.array([[10], [10], [10], [10], [10]])

# Procedimiento
capacidad_calorifica_agua = np.array([[0.45]])
capacidad_calorifica_acero = np.array([[4.2]])
capacidad_calorifica_aluminio = np.array([[0.90]])

#Salida
print(f"Capacidad calorifica del agua: {masa_agua @ capacidad_calorifica_agua}." + \
      f"\nCapacidad calorifica del acero: {masa_acero @ capacidad_calorifica_acero}" + \
        f"\nCapacida calorifica del aluminio: {masa_aluminio @ capacidad_calorifica_aluminio}.")

Capacidad calorifica del agua: [[49.5 ]
 [45.  ]
 [45.45]
 [44.37]
 [44.73]].
Capacidad calorifica del acero: [[1050.]
 [1050.]
 [1050.]
 [1050.]
 [1050.]]
Capacida calorifica del aluminio: [[9.]
 [9.]
 [9.]
 [9.]
 [9.]].


### Ejercicio 2
El peso molecular ($MW$) de cualquier compuesto es la suma de los productos del número de átomos de cada elemento ($Z$) y el peso atómico ($AW$) de cada elemento presente en el compuesto, o

$$MW = \sum^n_{i=1} AW_i \cdot Z_i$$

En la tabla se mencionan las composiciones de los primeros cinco alcoholes de cadena recta. Use los pesos atómicos del carbono, hidrógeno y oxígeno (12, 1 y 16,  respectivamente) y la multiplicación matricial para determinar el peso molecular (más  correctamente llamada masa molar) de cada alcohol.

<figure style="text-align: center;">
  <div><strong>Fig. 3.</strong> Composición de alcoholes. </div>
  <img src="markdown_resources\4.png" style="width: 45%; height: auto;">
  <figcaption>Tomado de MATLAB para Ingenieros de Holly Moore.</A>.</figcaption>
</figure>

*Ejercicio tomado de Moore, 2007.*

### Solución

In [10]:
# Entrada
compuestos = np.array([[1, 4, 1], [2, 6, 1], [3, 8 , 1], [4, 10, 1], [5, 12, 1]])
compuestos
pesos_atm = np.array([[12], [1], [16]])

#Procedimiento
calculo = compuestos @ pesos_atm
# [[["Metanol"],["Etanol"], ["Propanol"], ["Butanol"], ["Pentanol"] ]] 
print(calculo)

[[32]
 [46]
 [60]
 [74]
 [88]]


## Solución de sistemas de ecuaciones
### Ejercicio 1
Resolver el siguiente sistema de ecuaciones lineales.

$$
\begin{aligned}
2x_1 + 2x_2 - 3x_3 + 5x_4 + 8x_5 &= -2 \\
9x_1 - 3x_2 - 3x_3 - 8x_4 + 2x_5 &= 1 \\
7x_1 + 5x_2 - 7x_3 - 3x_4 + 9x_5 &= -15 \\
3x_1 - 2x_2 + 2x_3 - 5x_4 + 7x_5 &= 0 \\
2x_1 - 4x_2 + 9x_3 - 9x_4 + 6x_5 &= 7
\end{aligned}
$$

### Solución

In [15]:
A = np.array([[2, 2, -3, 5, 8],
              [9, -3, -3, -8, 2],
              [7, 5, -7, -3, 9],
              [3, -2, 2, -5, 7],
              [2, -4, 9, -9, 6]])
b = np.array([[-2], [1], [-15], [0], [7]])

x = np.linalg.solve(A, b)

print(f"Solution:\n {x}")

Solution:
 [[ 1.37805907]
 [-1.25274262]
 [ 1.46624473]
 [ 1.22151899]
 [-0.49493671]]


### Ejercicio 2
Suponga que una economía consiste en los sectores de carbón, electricidad y acero, y que el rendimiento de cada sector se distribuye entre los diferentes  sectores como en la tabla, donde las entradas de una columna representan fracciones de la producción total de un sector. La segunda columna de la tabla, por ejemplo, muestra que la producción total de electricidad se divide como sigue: un 40% de carbón, un 50% de acero, y el restante 10% de electricidad. (El sector eléctrico trata este 10% como un gasto en que incurre para hacer funcionar su negocio.) Ya que debe tomarse en cuenta la producción total, las  fracciones decimales de cada columna deben sumar 1. Los precios (es decir, valores en moneda) de la producción total de los sectores de carbón, electricidad y acero se denotarán como $p_C$, $p_E$ y $p_S$, respectivamente. Si es posible, encuentre los precios de equilibrio que permiten a los ingresos de cada sector  igualar sus gastos.

<figure style="text-align: center;">
  <div><strong>Fig. 4.</strong> Una economía sencilla. </div>
  <img src="markdown_resources\5.png" style="width: 35%; height: auto;">
  <figcaption>Tomado de Álgebra linea y sus aplicaciones de David C. Lay.</A>.</figcaption>
</figure>

**Recomendación:** Empezar generando manualmente las ecuaciones de cada columna. Por ejemplo, la primera columna responde a la ecuación $p_C = 0.0p_C + 0.6p_E + 0.4p_S$. Luego reordenar las ecuaciones y variables para generar el sistema matricial y resolverlo.

**Nota:** Este ejercicio corresponde a las aplicaciones de sistemas de ecuaciones lineales en economía, específicamente al *modelo de intercambio sencillo*, desarrollado por Leontief.

*Ejercicio tomado de Lay, 2007.*

### Solución

In [16]:
import numpy as np

# Definir la matriz de coeficientes
A = np.array([[1, -0.6, -0.4],
              [-0.4, 0.9, -0.5],
              [-0.3, -0.5, 0.8]])

# Definir el vector de términos independientes (todos ceros)
b = np.zeros(3)

# Calcular la solución del sistema utilizando valores propios (para encontrar soluciones no triviales)
eigenvalues, eigenvectors = np.linalg.eig(A)

# Verificar si el determinante es cero (sistema homogéneo con soluciones no triviales)
det_A = np.linalg.det(A)

det_A, eigenvectors[:, np.argmin(np.abs(eigenvalues))]  # Tomar el vector propio asociado al menor valor propio


(np.float64(7.549516567451048e-17),
 array([0.57735027, 0.57735027, 0.57735027]))